#!/bin/bash

# The script runs a vector-store node in an AWS instance.

set -e

envs=$1
[[ -f $envs ]] || (echo envs file not provided ; exit 1)
source $envs

idx=$2
[[ -z $idx ]] && (echo idx not provided ; exit 1)

ip_ext=VS_IP_${idx}_EXT
ip_ext=${!ip_ext}
ip_db=DB_IP_${idx}_INT
ip_db=${!ip_db}

# run vs in docker
ssh ubuntu@$ip_ext sudo docker run --rm -d \
    --name vs \
    --ulimit nofile=4294967295:4294967295 \
    -p 6080:6080 \
    -e VECTOR_STORE_URI=0.0.0.0:6080 \
    -e VECTOR_STORE_SCYLLADB_URI=$ip_db:9042 \
    $VS_DOCKER_IMAGE
