#!/bin/bash

# The script runs a scylla node in an AWS instance.

set -e

envs=$1
[[ -f $envs ]] || (echo envs file not provided ; exit 1)
source $envs

idx=$2
[[ -z $idx ]] && (echo idx not provided ; exit 1)

ip_ext=DB_IP_${idx}_EXT
ip_ext=${!ip_ext}
ip_int=DB_IP_${idx}_INT
ip_int=${!ip_int}
ip_vs=VS_IP_${idx}_INT
ip_vs=${!ip_vs}

# setup seeds for scylla cluster if setup for second or later node
[[ $idx -gt 0 ]] && seeds="--seeds=$DB_IP_0_INT"

ssh ubuntu@$ip_ext bash <<EOF
echo "dc=datacenter1" > /home/ubuntu/cassandra-rackdc.properties
echo "rack=rack$idx" >> /home/ubuntu/cassandra-rackdc.properties
EOF

# run scylla in docker
ssh ubuntu@$ip_ext docker run --rm -d \
    --name scylla \
    -v /mnt/data/scylla:/var/lib/scylla \
    -v /home/ubuntu/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties:ro \
    -p 7000:7000 \
    -p 7001:7001 \
    -p 7199:7199 \
    -p 9042:9042 \
    -p 9160:9160 \
    -p 10000:10000 \
    -p 19042:19042 \
    $SCYLLA_DOCKER_IMAGE \
        --vector-store-primary-uri http://$ip_vs:6080 \
        --batch-size-warn-threshold-in-kb=1024 \
        --broadcast-address $ip_int \
        --broadcast-rpc-address $ip_int \
        --rf-rack-valid-keyspaces true \
        --endpoint-snitch GossipingPropertyFileSnitch \
        $seeds
