#!/bin/bash

# This script installs cargo tools for using in CI environments.

CARGO_TOOLS=(
    "cargo-deny"
    "cargo-machete"
    "cargo-cyclonedx"
)

cargo install --locked "${CARGO_TOOLS[@]}" "$@"
