name: Daily

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

  merge_group:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full
