name: Daily

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

  merge_group:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full

jobs:
  empty:
    runs-on: ubuntu-latest
    steps:
      - name: Empty step
        run: echo "This is a daily workflow that runs at midnight."
